logging:
  level:
    root: warn
    com.example.bankcards.BankCards: info
    org.springframework.web: error
    org.springframework.security: debug
    liquibase: error
    #org.springframework.security.core.userdetails: debug
    com.example.bankcards.security.AppUserPrincipal: trace
    com.example.bankcards.controller.UserController: trace
server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
  application:
    name: BankRestApp
    version: 1.0
  jpa:
    show-sql: false
    open-in-view: on
    database: postgresql
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    name: bankrest
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/bankrest?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS public
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/bankrest
    user: admin
    password: admin
    change-log: classpath:/db/migration/db.changelog-master.xml

app:
  security:
    type: db